[project]
name = "baffle"
version = "0.1.0"
description = "A rules engine for composable event-driven simulations"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [{name = "thom.l.lake@gmail.com"}]
dependencies = []

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.16.0",
    "pytest>=9.1.1",
    "readchar>=4.2.2",
]
